# Generated by Django 3.2.5 on 2021-12-08 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20211208_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_session',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_session',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_del', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking_session',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking_session',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
